language: python
python:
  - "3.6"
install: 
  - pip install --upgrade databricks-cli
script: 
  - python -c "dummy=0"
deploy:
  - provider: script
    script: bash databricks/1_deploy/deploy_job.sh -r "westeurope" -t $DATABRICKS_TOKEN -j "job.daily.config.json"
    on:
      all_branches: true